LangString ProductDescription ${LANG_RUSSIAN} "Remote Docker переносит выполнение Docker с Mac на этот Windows-компьютер в локальной сети."
LangString InstallLocationTitle ${LANG_RUSSIAN} "Куда установить Remote Docker"
LangString InstallLocationHelp ${LANG_RUSSIAN} "Выберите одну основную папку. Внутри неё установщик создаст папки App для приложения и Data для Docker, WSL, образов и контейнеров."
LangString SelectBaseDirectory ${LANG_RUSSIAN} "Выберите основную папку Remote Docker"
LangString BrowseButton ${LANG_RUSSIAN} "Обзор..."
LangString CreateDesktopShortcut ${LANG_RUSSIAN} "Создать ярлык на рабочем столе"
LangString InvalidBaseDirectory ${LANG_RUSSIAN} "Выберите папку внутри существующего диска, а не корень диска."
LangString InstallingFiles ${LANG_RUSSIAN} "Установка файлов приложения"
LangString ProvisioningWSL ${LANG_RUSSIAN} "Подготовка изолированной среды WSL 2"
LangString ConfiguringDocker ${LANG_RUSSIAN} "Подготовка Docker Engine"
LangString ConfiguringFirewall ${LANG_RUSSIAN} "Настройка доступа только из частной локальной сети"
LangString CreatingShortcuts ${LANG_RUSSIAN} "Создание ярлыков"
LangString InstallRetry ${LANG_RUSSIAN} "Подготовка не завершилась. Повторить попытку?"
LangString InstallLogPath ${LANG_RUSSIAN} "Журнал установки:"
LangString RebootRequired ${LANG_RUSSIAN} "Windows-компоненты включены. Перезагрузите компьютер и снова запустите этот установщик."
LangString InstallFailed ${LANG_RUSSIAN} "Установка Remote Docker не завершена."
