LangString ProductDescription ${LANG_RUSSIAN} "Remote Docker переносит выполнение Docker с Mac на этот Windows-компьютер в локальной сети."
LangString PreflightTitle ${LANG_RUSSIAN} "Проверка перед установкой"
LangString PreflightBody ${LANG_RUSSIAN} "Мастер проверит Windows 10/11 x64, поддержку виртуализации, WSL 2 и свободное место. Если для включения системных компонентов потребуется перезагрузка, установка сохранит только одноразовую отметку продолжения."
LangString SelectDataDirectory ${LANG_RUSSIAN} "Папка данных Docker и WSL"
LangString SelectDataDirectoryHelp ${LANG_RUSSIAN} "Здесь будут храниться Linux-система, образы, контейнеры и данные Docker. Выберите диск с достаточным свободным местом."
LangString InvalidDataDirectory ${LANG_RUSSIAN} "Укажите абсолютный путь к папке данных."
LangString VirtualizationPreflight ${LANG_RUSSIAN} "Поддержка виртуализации и WSL 2 будет проверена перед изменением системы."
LangString InstallingFiles ${LANG_RUSSIAN} "Установка файлов приложения"
LangString ProvisioningWSL ${LANG_RUSSIAN} "Подготовка изолированной среды WSL 2"
LangString ConfiguringDocker ${LANG_RUSSIAN} "Подготовка Docker Engine"
LangString ConfiguringFirewall ${LANG_RUSSIAN} "Настройка доступа только из частной локальной сети"
LangString CreatingShortcuts ${LANG_RUSSIAN} "Создание ярлыков"
LangString InstallRetry ${LANG_RUSSIAN} "Подготовка не завершилась. Повторить попытку?"
LangString InstallLogPath ${LANG_RUSSIAN} "Журнал установки:"
LangString RebootRequired ${LANG_RUSSIAN} "Windows-компоненты включены. Перезагрузите компьютер и снова запустите этот установщик."
LangString InstallFailed ${LANG_RUSSIAN} "Установка Remote Docker не завершена."
LangString DesktopShortcutName ${LANG_RUSSIAN} "Создать ярлык на рабочем столе"
