Port 22
Protocol 2
PubkeyAuthentication yes
AuthenticationMethods publickey
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
AllowUsers remote-docker
AuthorizedKeysFile /var/lib/remote-docker/authorized_keys
HostKey /run/remote-docker/ssh_host_ed25519_key
PermitTTY no
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding yes
PermitOpen 127.0.0.1:*
PermitListen 127.0.0.1:*
GatewayPorts clientspecified
ForceCommand /usr/local/libexec/remote-docker/authorized-command
